seed_everything: 4141910080
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 2
  num_nodes: 1
  precision: 16-mixed
  accumulate_grad_batches: 4
  max_epochs: -1
  fast_dev_run: false
  min_epochs: null
  max_steps: 200_000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: 20
  limit_predict_batches: 14
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 50
  enable_checkpointing: true
  enable_progress_bar: false
model:
  vae_chkp: xvjiarui/ldm-vq-f4
  base_channels: 128
  base_channels_multiples:
  - 1
  - 2
  - 4
  - 4
  n_layers: 2
  n_heads: 4
  use_cross_attn: False
  pixel_shuffle: False
  vae_quantization: True
  dropout_rate: 0.0
  scale_factor: 16
  use_scale_shift_norm: False
  timesteps: 15
  scheduler_type: one_cycle
  lr: 1e-5
data:
  class_path: data.MultiImageDataModule
  init_args:
    data_dir: ../thermalx16/thermal
    splits:
    - train
    - val
    - test
    classes:
    - LR_x16
    - visible
    - GT
    batch_size: 4
ckpt_path: checkpoints/resshift_imagenet.ckpt
