seed_everything: 4141910080
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true 
  num_nodes: 1
  devices: 2
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ./
      version: resshift_imagenet_maxvitn1_wd_vq_compact_tiny_x0_cont
  accumulate_grad_batches: 2
  max_epochs: -1
  fast_dev_run: null
  min_epochs: null
  max_steps: 150_000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: 0
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: null
  num_sanity_val_steps: 5
  log_every_n_steps: 5000
  enable_checkpointing: true
  enable_progress_bar: false
model:
  pred_x0: True
  vae_chkp: xvjiarui/ldm-vq-f4
  vae_type: vqvae
  compact_model: True
  max_vit_attn: True
  n_heads: 1
  max_vit_attn: True
  base_channels: 128
  base_channels_multiples:
  - 1
  - 2
  - 2
  - 4
  n_layers: 1
  apply_attention:
    - True
    - True
    - True
    - False
  use_cross_attn: False
  pixel_shuffle: False
  window_size: 4
  dropout_rate: 0.0
  scale_factor: 4
  use_scale_shift_norm: False
  timesteps: 15
  scheduler_type: one_cycle
  lr: 5e-5
  image_size: 256
data:
  class_path: data.SimpleImageDataModule
  init_args:
    data_dir: ../Imagenet/CLS-LOC/
    train_img_list: ../Imagenet/train_filter_256.txt
    valid_img_list: ../Imagenet/val_filter_256.txt
    test_img_list: ../Imagenet/test_filter_256.txt
    batch_size: 8
    img_size: 256
    num_workers: 24
ckpt_path: 
