seed_everything: 4141910080
trainer:
  accelerator: gpu
  # _find_unused_parameters_true 
  strategy: ddp_find_unused_parameters_true 
  num_nodes: 1
  devices: 2
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ./
      version: resshift_imagenet_windowedn1_wd_novae_eps_fix_try
  accumulate_grad_batches: 4
  max_epochs: -1
  fast_dev_run: null
  min_epochs: null
  max_steps: 150_000
  min_steps: null
  max_time: null
  limit_train_batches: 200
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 5
  log_every_n_steps: 100
  enable_checkpointing: true
  enable_progress_bar: false
model:
  base_channels: 128
  base_channels_multiples:
  - 1
  - 2
  - 4
  - 4
  n_layers: 2
  n_heads: 1
  apply_attention:
    - True
    - True
    - True
    - False
  use_cross_attn: False
  pixel_shuffle: False
  window_size: 8
  max_vit_attn: True
  dropout_rate: 0.0
  scale_factor: 4
  use_scale_shift_norm: False
  timesteps: 15
  scheduler_type: one_cycle
  lr: 8e-5
data:
  class_path: data.SimpleImageDataModule
  init_args:
    data_dir: ../Imagenet/CLS-LOC/
    train_img_list: ../Imagenet/train_filter_256.txt
    valid_img_list: ../Imagenet/val_filter_256.txt
    test_img_list: ../Imagenet/test_filter_256.txt
    batch_size: 2
    img_size: 256
    num_workers: 24
ckpt_path:
