seed_everything: 4141910080
trainer:
  accelerator: gpu
  # _find_unused_parameters_true 
  strategy: ddp
  num_nodes: 1
  devices: 2
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ./
      version: resshift_imagenet_pixart_novae
  accumulate_grad_batches: 8
  max_epochs: -1
  fast_dev_run: false
  min_epochs: null
  max_steps: 200_000
  min_steps: null
  max_time: null
  limit_train_batches: 0.5
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 5_000
  enable_checkpointing: true
  enable_progress_bar: false
model:
  scale_factor: 4

  n_layers: 16
  n_heads: 8
  patch_size: 4
  use_cross_attn: False
  window_size: 0
  input_size: 256
  input_chs: 3
  hidden_size: 768
  scale_factor: 4
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  drop_path: 0.1
  window_size: 0
  window_block_indexes: null
  use_rel_pos: False
  cond_channels: 3
  cond_img_size: 64
  lewei_scale: 1.0
  
  timesteps: 15
  scheduler_type: null
  lr: 8e-5
data:
  class_path: data.SimpleImageDataModule
  init_args:
    data_dir: ../Imagenet/CLS-LOC/
    train_img_list: ../Imagenet/train_filter_256.txt
    valid_img_list: ../Imagenet/val_filter_256.txt
    test_img_list: ../Imagenet/test_filter_256.txt
    batch_size: 4
    img_size: 256
    num_workers: 24
ckpt_path:
