seed_everything: 4141910080
trainer:
  accelerator: gpu
  # _find_unused_parameters_true 
  strategy: ddp_find_unused_parameters_true
  num_nodes: 1
  devices: 2
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ./
      version: resshift_imagenet_wd_vq_pixartcat_960_x0_p2
  accumulate_grad_batches: 2
  max_epochs: -1
  fast_dev_run: false
  min_epochs: null
  max_steps: 150_000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 5
  log_every_n_steps: 5_000
  enable_checkpointing: true
  enable_progress_bar: false
model:
  pred_x0: True
  vae_chkp: xvjiarui/ldm-vq-f4
  vae_type: vqvae
  input_size: 64
  patch_size: 2
  hidden_size: 960
  n_layers: 8
  n_heads: 8
  scale_factor: 4
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  drop_path: 0.1
  window_size: 0
  window_block_indexes: null
  use_rel_pos: false
  lewei_scale: 1.0
  lr: 2e-05
  scheduler_type: null
  timesteps: 15
  resshift_p: 0.3
  kappa: 2.0
  image_size: 256
data:
  class_path: data.SimpleImageDataModule
  init_args:
    data_dir: ../Imagenet/CLS-LOC/
    train_img_list: ../Imagenet/train_filter_256.txt
    valid_img_list: ../Imagenet/val_filter_256.txt
    test_img_list: ../Imagenet/test_filter_256.txt
    batch_size: 8
    img_size: 256
    num_workers: 24
ckpt_path: 
