seed_everything: 4141910080
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 1
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ./
      name: vae_test_logs
      version: test_vqvae2
model:
  vae_chkp: xvjiarui/ldm-vq-f4
  use_quantization: True
data:
  data_dir: ../Imagenet/CLS-LOC/
  train_img_list: ../Imagenet/train_filter_256.txt
  valid_img_list: ../Imagenet/val_filter_256.txt
  test_img_list: ../Imagenet/test_filter_256.txt
  num_workers: 24
  batch_size: 16
  img_size: 256
ckpt_path: null
